### ISSUE TITLE
You appear to have made an error in this configuration.

### ISSUE THREAD

**Issue by briancw** [Narkoleptika/eslint-config-narkoleptika#1]
https://github.com/Narkoleptika/eslint-config-narkoleptika/blob/bb1f42bf350d16e3ecd9314b639a3d1ac6451b8f/index.js#L39

The correct setting is [2, 'always-multiline']

**Comment by Narkoleptika** [comment]
After thorough analysis of your issue, I have come to the conclusion that your perception of correct is incorrect. In fact it would appear that you have an inadequate grasp on reality in general, as it is difficult to get a grip with all of the drool that must accumulate on your hands from your mouth as you breath.

With that in mind, I will be closing this issue. However, if proper concepts continue to confuse and frighten you, feel free to respond with any further questions that you may have.

**Comment by Narkoleptika** [comment]
It would appear that I was mistaken (c3849ea7897374d648f9d2950b7017326f91c354) and my aggressive "joke" response is now very cringe.

**Comment by briancw** [comment]
No cringe. This is still extremely funny.
